### ISSUE TITLE
Modules ?

### ISSUE THREAD

**Issue by CoderZ90** [Rachit333/hand_gesture_mouse_control#1]
What module i need to install ( i am using vscode )

**Comment by Rachit333** [comment]
You would need 
**cv2**
**mediapipe**
**time**
**autopy**
**numpy**
**math**
**pyautogui or other mouse controlling library**
**pycaw**

**Comment by CoderZ90** [comment]
It is showing pyautogui as pt ( No module found ) ? you know why is this >?

**Comment by CoderZ90** [comment]
If you want i can share the screenshot

**Comment by CoderZ90** [comment]
![image](https://user-images.githubusercontent.com/62499625/123046312-955b6d80-d419-11eb-9ac7-79f110906d2e.png)

It is showing this :(

**Comment by Rachit333** [comment]
For pyautogui problem write: 
pip install pyautogui
