### ISSUE TITLE
Unable to install autopy :(

### ISSUE THREAD

**Issue by CoderZ90** [Rachit333/hand_gesture_mouse_control#2]
This is what happening i

i am using *pip install autopy* but it is not installing

(VSCODE)

**Comment by Rachit333** [comment]
i dont use VSCode so i will have to look it up... :) please wait

**Comment by Rachit333** [comment]
Can you please type what is the error showing?

**Comment by CoderZ90** [comment]
> Can you please type what is the error showing?

Yes 2 minutes

**Comment by CoderZ90** [comment]
![image](https://user-images.githubusercontent.com/62499625/123046412-b459ff80-d419-11eb-9793-5b8d9f1185ca.png)

It is showing this and i am not able to install autopy also

**Comment by Rachit333** [comment]
whats the error showing when you write pip install autopy?

**Comment by Rachit333** [comment]
Idk what's the problem in your pc but I uninstalled **autopy** and reinstalled it and went smoothly :> Please search on _stackoverflow_ if you haven't figured it out yet. :)

**Comment by CoderZ90** [comment]
> Idk what's the problem in your pc but I uninstalled **autopy** and reinstalled it and went smoothly :> Please search on _stackoverflow_ if you haven't figured it out yet. :)

What version of python you are using ?

**Comment by CoderZ90** [comment]
> > Idk what's the problem in your pc but I uninstalled **autopy** and reinstalled it and went smoothly :> Please search on _stackoverflow_ if you haven't figured it out yet. :)
> 
> What version of python you are using ?

in version 3.9 it is giving me error but autpoy can be installed in version 3.7.9 but then the other problem is i cant install other modules

**Comment by Rachit333** [comment]
yeah i forgot to mention that... my bad i am running the same python 3.7.9

**Comment by Rachit333** [comment]
> > > Idk what's the problem in your pc but I uninstalled **autopy** and reinstalled it and went smoothly :> Please search on _stackoverflow_ if you haven't figured it out yet. :)
> > 
> > 
> > What version of python you are using ?
> 
> in version 3.9 it is giving me error but autpoy can be installed in version 3.7.9 but then the other problem is i cant install other modules

which module you are not able to install?

**Comment by Rachit333** [comment]
And also i have updated the code because i was testing something in my code and forgot it there...

**Comment by CoderZ90** [comment]
oh wait lemme check the updatedone

**Comment by CoderZ90** [comment]
Hey ! it worked
